### ISSUE TITLE
Undefined variables, ax_logo and ax_align

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/axioma#2]
Thanks for this nice looking theme! I've installed and enabled it on a test site, and when I visit a page I get two error messages:

- Undefined variable: ax_logo in include() (line 27 of /path-to-backdrop/themes/axioma/templates/header.tpl.php)
- Undefined variable: ax_align in include() (line 23 of /path-to-backdrop/themes/axioma/templates/block.tpl.php)

The messages appear also after changing the header and menu related theme settings.

**Comment by olafgrabienski** [comment]
Now also tested with a vanilla demo site built from https://backdropcms.org/demo. After installing, enabling and default setting the theme, I see similar messages on `admin/reports/dblog` referring to regular page visits.

**Comment by olafgrabienski** [comment]
@korontari That was quick! I've applied the PR on my test site – seems to work fine (no more messages).

**Comment by korontari** [comment]
@olafgrabienski , thank you for testing!

**Comment by Egmund** [comment]
Well -- years later:
`Warning: Undefined variable $ax_logo i include() (linje 24`

Newest version and everything is also updated to latest.

**Comment by Egmund** [comment]
Sorry - that might take some time. I manage about 20 websites w. backdrop and forgot which one the error occurred on - and why (probably disabled the logo).
Will test though.
