### ISSUE TITLE
Front Page with new content type

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/axioma#4]
FYI

![axioma-cards](https://user-images.githubusercontent.com/3144571/165410869-5ddf2473-cbdf-4dd3-8536-373a53d2e46c.png)

**Comment by korontari** [comment]
@stpaultim , thank you for informing me about this! I see there is a new content type that comes by default with the CMS. I will have a look at it. Let me know if you have any specific feedback apart from the need to style new elements.

**Comment by stpaultim** [comment]
I just want to be sure that all contrib developers are aware of this change and have the opportunity to make adjustments. 

This new content type and front page view have been merged into the dev branch and will be part of the 1.22.0 release on May 15th. This means we still have a little over two weeks to fix any bugs that we find or to make improvements. 

Please, let us know in the core issue queue if find any issues that need to be fixed in core or if you have ideas for improvement.
