### ISSUE TITLE
Menu doesn't show on Iphone-Safari 

### ISSUE THREAD

**Issue by peregri2** [backdrop-contrib/axioma#5]
Hi
The primary menú doesn't show on Iphone-Safari and the dropdown menu shows without colour on windows/firefox. Is there any solution?

Thankyou

**Comment by korontari** [comment]
Hi @peregri2 ,
Thank you for reporting this! I need to look more closely into that. Just to ensure I am on the same page, do you have the latest version of Backdrop installed and database updated?

**Comment by peregri2** [comment]
Thank you! I have Backdrop 1.22.2

![Captura de Pantalla 2022-09-04 a les 16 54 56](https://user-images.githubusercontent.com/112721940/188319842-b3ac9d15-4da9-4573-a903-4f030f2efe5b.png)

**Comment by korontari** [comment]
@peregri2 , could you please test PR #6 and check if the primary menu shows up on mobile safari?

Also I need more info on dropdown menu not showing on  windows/firefox. I was not able to reproduce the bug and I wonder if you have a working setup where I can observe the bug? Or could you provide a screenshot where it is visible?

**Comment by korontari** [comment]
I have made a release that fixes the bug. Please update the theme module and feel free to reopen the issue if the bug is still present.
